// hexo-script-remove-p-in-li.js
// Remmove extra <p> tags in list items generated by markdown "loose list" behavior.

hexo.extend.filter.register('after_post_render', function(data) {
  // Replace <li><p>...</p> with <li>...
  // Uses [\s\S] to match newlines as well
  data.content = data.content.replace(/<li>\s*<p>([\s\S]*?)<\/p>/g, function(match, inner) {
    return '<li>' + inner;
  });
  return data;
});
